name: Release Creation

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      # Run build script
      - name: Build Packs
        run: |
          npm ci
          npm run build

      # Get all relevant files
      - name: Get Includes
        shell: bash
        id: get-includes
        run: echo "files=$(node ./.github/workflows/get-includes.js)" >> $GITHUB_OUTPUT

      # Get the version from 'module.json'
      - name: Get Version
        shell: bash
        id: get-version
        run: echo "::set-output name=version::$(node ./.github/workflows/get-version.js)"

      # Substitute the Manifest and Download URLs in the `module.json`.
      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_version
        uses: devops-actions/variable-substitution@v1.2
        with:
          files: wtrpg-complete-compendium/module.json
        env:
          version: ${{steps.get-version.outputs.version}}
          manifest: https://github.com/${{ github.repository }}/releases/latest/download/module.json
          download: https://github.com/${{ github.repository }}/releases/download/${{steps.get-version.outputs.version}}/module.zip

      # Create a folder containing all the module stuff and zip it for the release
      - name: Create Zip
        run: cd wtrpg-complete-compendium; zip -r ../module.zip ./

      # Create a release for this specific version
      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{steps.get-version.outputs.version}}
          allowUpdates: false
          omitDraftDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          name: ${{steps.get-version.outputs.version}}
          body: ${{ steps.changelog.outputs.release-notes }}
          artifacts: './wtrpg-complete-compendium/module.json, ./module.zip'
          makeLatest: true